# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbdbdf261482e0794e17db607e53ad167004af35f9ba102d4609d3c22813cb7020c8b3630cdd1571025a53c2dee14f65dfa0f4b85fe4647ad029ba5fa642ca4f

test:
  secret_key_base: e565626ab37e5f35c4735129692859ab393eb5bc7bef7cedb437fe1ba415a31633a45249bd45dcf9feff8ae1082a6e35999745933a285288a880442b54c862db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
